using System.Net.Http;
using System.Net.Http.Headers;

namespace pdf_generator.Factories
{
    public class DocumentExtractionHttpRequestFactory : IDocumentExtractionHttpRequestFactory
    {
        public HttpRequestMessage Create(string requestUri)
        {
            var request = new HttpRequestMessage(HttpMethod.Post, requestUri);
            request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6ImpTMVhvMU9XRGpfNTJ2YndHTmd2UU8yVnpNYyIsImtpZCI6ImpTMVhvMU9XRGpfNTJ2YndHTmd2UU8yVnpNYyJ9.eyJhdWQiOiJhcGk6Ly9mYS1kcC1jbXMtZG9jLXNlcnZpY2VzLWRldiIsImlzcyI6Imh0dHBzOi8vc3RzLndpbmRvd3MubmV0LzAwZGQwZDFkLWQ3ZTYtNDMzOC1hYzUxLTU2NTMzOWM3MDg4Yy8iLCJpYXQiOjE2NDcyNzU4ODQsIm5iZiI6MTY0NzI3NTg4NCwiZXhwIjoxNjQ3Mjc5ODQxLCJhY3IiOiIxIiwiYWlvIjoiQVZRQXEvOFRBQUFBampSTjRJMmhrMENYRk90TWJsVko4Ky83aWorNUdDWXhUN1BQemNieXBvOVlJOGtRU1RLRG5CK1BxTHFEYmI2ZU5RUmllTHJJSFl3cnBKMjd2Vmh2dHJ4bk8rNkt0cVQyWGV3TzhEQU1uVkE9IiwiYW1yIjpbInB3ZCIsIm1mYSJdLCJhcHBpZCI6IjA0YjA3Nzk1LThkZGItNDYxYS1iYmVlLTAyZjllMWJmN2I0NiIsImFwcGlkYWNyIjoiMCIsImZhbWlseV9uYW1lIjoiQmFsbWVyIChBZG1pbikiLCJnaXZlbl9uYW1lIjoiTWFydHluIiwiaXBhZGRyIjoiMi4yNC4xMTIuMTkiLCJuYW1lIjoiTWFydHluIEJhbG1lciAoQWRtaW4pIiwib2lkIjoiM2NmMGY5MGEtMGU4Zi00YTM0LTgwNmUtMGJkZWE5YTViNWM0IiwicmgiOiIwLkFTQUFIUTNkQU9iWE9FT3NVVlpUT2NjSWpGU0x0dlJpMm10SnVnT0Q0UTFSLXJ3Z0FBMC4iLCJyb2xlcyI6WyJhcHBsaWNhdGlvbi5yZWFkIl0sInNjcCI6InVzZXJfaW1wZXJzb25hdGlvbiIsInN1YiI6InFVQnQ5QmVWeE5HN1NaTDJSOWF4a3VCRERicTREbVJJcDhIT19kQ1JxWDAiLCJ0aWQiOiIwMGRkMGQxZC1kN2U2LTQzMzgtYWM1MS01NjUzMzljNzA4OGMiLCJ1bmlxdWVfbmFtZSI6ImEubWJhbG1lckBDUFNHT1ZVSy5vbm1pY3Jvc29mdC5jb20iLCJ1cG4iOiJhLm1iYWxtZXJAQ1BTR09WVUsub25taWNyb3NvZnQuY29tIiwidXRpIjoiUXZFT2VSWG1tRXVCcG9uXzU1UlRBQSIsInZlciI6IjEuMCJ9.QuDsHlMyGL9Lp-ughQwz-HdY9dJrZJSZM_-X0iV4ErtAtgWFbrH8EnYQz5vcjTppNyiTAvVT5W1VjQXIgV6s3B_OMGXJpK_jriNAUvuPC7t-63-n5Z0lcv65RsdzPy15sZrVaMSdwKWa6xfe6jOF_ppz3cmTuZPsOkvWacEDjWpM7-UHEsWWBzs5NCEj6HHvZNNFuuw8fzkqaDtb4Oxz9scI23jz0hAOYiQkD3VtmakmjzAvsjRssgxJn280G0LsSDCK21cTwmxLtSz2kSfFRSnesNnyoCcw8N9NXQdvL4t-sjVsP_XNJQKts-nJWLfWkYoR-63I4oKCO3LCdBLAYw");
            return request;
        }
    }
}
